version: "3.9"
services:
  db:
    image: "postgres:13.4"
    restart: always
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user1
      - POSTGRES_PASSWORD=pwd
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
